-- Seeding data from sqlite

DELETE FROM personal_info;
DELETE FROM experience;
DELETE FROM education;
DELETE FROM certificates;
DELETE FROM projects;
DELETE FROM social_links;

-- Data for personal_info
INSERT INTO personal_info (name, birthday, address, age, degree, contact, email, linkedin, github, facebook, instagram, resume_url) VALUES ('Tristan Sangangbayan', 'August 31, 2000', 'Indang, Cavite', 25, 'Bachelor of Science in Information Technology', '(+63) 907-220-3266 | (+63) 976-145-9388', 'sangangbayant@gmail.com', 'https://www.linkedin.com/in/tristansangangbayan/', 'https://github.com/dlxks', 'https://www.facebook.com/dot3stan/', 'https://www.instagram.com/dot3stan/', '');

-- Data for experience
INSERT INTO experience (company, position, duration, description) VALUES ('AIA Philippines – Crizaldo Financial Associates ', 'Intern – Graphic Designer/Digital Marketer', 'February 2022 – May 2022', '["Aided the marketing team in creating graphic design and visual content for printed materials, banners, brochures, and calendars used for promoting the agency. Created graphics were used as promotional materials for digital marketing.","Utilized social media platforms and online office tools to promote the agency and encourage individuals to avail the products and services of the agency. Approximately 40 individuals were encouraged to attend the free webinar of the company."]');
INSERT INTO experience (company, position, duration, description) VALUES ('Freelance', 'Web Developer', 'January 2025 – January 2026', '["Designed and developed a web-based parish transaction and reservation system using PHP, MySQL, HTML, CSS, and JavaScript to manage event bookings, payments, and records.","Implemented responsive, mobile-friendly layouts ensuring consistent performance across devices.","Optimized PHP scripts and MySQL queries, improving load times and system performance."]');
INSERT INTO experience (company, position, duration, description) VALUES ('Freelance', 'Graphic Designer', 'January 2024 – present', '["Created custom wedding and birthday invitations, logos, and marketing graphics for small businesses, including a milk tea store.","Designed banners and tarpaulins for events and promotions, ensuring print-ready quality.","Delivered visually compelling work using Adobe Photoshop, and Adobe InDesign, meeting tight client deadlines."]');
INSERT INTO experience (company, position, duration, description) VALUES ('Schneider Electric', 'Order Entry Administrator', 'June 2023 – April 2025', '["Supported internal digital systems and streamlined order processing using SAP S/4HANA, ensuring accuracy and efficiency in cross-functional operations.","Collaborated across departments to resolve order discrepancies, automate workflows, and improve system reliability—skills transferable to software and system process optimization.","Led onboarding sessions and provided technical guidance to new hires, including system navigation and data entry best practices.","Acted as a key support point for digital operations, reflecting adaptability, attention to detail, and the ability to manage complex systems—valuable traits for backend and systems development roles."]');

-- Data for education
INSERT INTO education (school, location, level, degree, duration, grade) VALUES ('Cavite State University-Indang Campus', 'Indang, Cavite', 'Tertiary', 'Bachelor of Science in Information Technology', '2018 - 2023', 1.323);
INSERT INTO education (school, location, level, degree, duration, grade) VALUES ('STI College Tagaytay', 'Tagaytay City, Cavite', 'Senior High School', 'TVL - ICT Computer Programming NC III - Java & .NET Technology', '2016 - 2018', 94);
INSERT INTO education (school, location, level, degree, duration, grade) VALUES ('Academia de San Vicente Ferrer ', 'Indang, Cavite', 'Junior High School', 'General Education', '2012 - 2016', 94);

-- Data for certificates
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Civil Service Professional Eligible', 'Civil Service Commission', 'August 2024', '');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Become a Professional React Developer', 'Scrimba - Coursera', 'August 2025', '/certificates/scrimba_professional_react_developer.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Meta Front-End Developer Professional Certificate', 'Meta - Coursera', 'August 2025', '/certificates/meta_front_end_developer.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Meta React Specialization', 'Meta - Coursera', 'July 2025', '/certificates/meta_react.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Foundations of User Experience (UX) Design', 'Google - Coursera', 'July 2025', '/certificates/foundations_of_ux_design.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Adobe Photoshop Basic Workflow', 'Department of Information and Communications Technology', 'March 11, 2022', '/certificates/adobe_photoshop_basic_workflow.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Maximizing the Basics of Programming: Decision, Loops, and the CRUD', 'Department of Information and Communications Technology', 'March 23, 2022', '/certificates/maximizing_the_basics_of_programming.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('How to Create a Simple Style Guide for Design-Development Hand-Off', 'StackLeague x GDG Cagayan de Oro', 'April 20, 2022', '/certificates/how_to_create_a_simple_style_guide.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Information Security Awareness Training', 'Department of Information and Communications Technology', 'March 30, 2022', '/certificates/information_security_awareness_training.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Learning Web Development, Top-Down', 'StackLeague x PWA Pilipinas', 'March 16, 2022', '/certificates/tech_session_learning_web_development.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Netiquettes: Code of Good Behavior', 'Department of Information and Communications Technology', 'April 8, 2022', '/certificates/netiquettes_code_of_good_behavior.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Roadmap to Senior Programmer', 'StackLeague x Coding Chief Career', 'April 28, 2022', '/certificates/roadmap_to_senior_programmer.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Building a Minimum Viable Product', 'StackLeague x BYTE ADMU', 'March 23, 2022', '/certificates/building_a_minimum_viable_product.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Web Development Using WordPress', 'Department of Information and Communications Technology', 'March 18, 2022', '/certificates/web_development_using_wordpress.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('Web Accessibility Done Right - Common Design Gaps and How to Fix Them', 'StackLeague x UXPH Tech Session', 'May 25, 2022', '/certificates/web_accessibility_done_right.pdf');
INSERT INTO certificates (title, provider, date, file_url) VALUES ('The Rise of Intelligent Automation', 'StackLeague x Phil IT Org Tech', 'April 13, 2022', '/certificates/the_rise_of_intelligent_automation.pdf');

-- Data for projects
INSERT INTO projects (title, technology, link, description) VALUES ('CVSU Entrance Exam System', 'Laravel, Vue.js, Tailwind CSS, BotMan, Twilio', 'https://github.com/dlxks/cvsu-ees.git', '["Prototype entrance exam platform developed for Cavite State University to digitize exam administration","Integrated a basic chatbot using BotMan and Twilio for guidance, FAQs, and automated student assistance","Fullstack web application built with Laravel (backend) and Vue.js (frontend), styled with Tailwind CSS"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Student Management System', 'HTML, CSS, JavaScript, PHP, MySQL', 'https://github.com/dlxks/sims.git', '["Web-based platform designed for managing student records and school-related data","Supports CRUD operations for student profiles including enrollment, grades, and personal details","Responsive front-end built with Bootstrap, with backend integration in PHP and MySQL database"]');
INSERT INTO projects (title, technology, link, description) VALUES ('React Portfolio', 'React, Bootstrap, AOS, Iconify', 'https://github.com/dlxks/react-portfolio.git', '["Responsive personal portfolio showcasing projects, skills, and experiences","Implemented smooth scroll animations using AOS for a dynamic user experience","Custom icon sets integrated with Iconify and styled with Bootstrap for modern design consistency"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Little Lemon Restaurant', 'React, Next.js, Tailwind CSS', 'https://github.com/dlxks/little-lemon.git', '["Restaurant-themed web application with features for table reservation, menu browsing, and booking management","Developed using Next.js 13 App Router for optimized routing and scalability","State management handled via Context API for persistent user sessions and cart functionality","Enhanced user experience with interactive UI components such as modals and toast notifications"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Memeify', 'React, CSS, HTML', 'https://github.com/dlxks/memeify.git', '["Lightweight meme generator enabling users to create, edit, and share custom memes instantly","Supports drag-and-drop image uploads with live preview functionality","Designed with a responsive layout ensuring seamless use across desktop and mobile devices"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Yummify', 'React, REST API, CSS', 'https://github.com/dlxks/yummify.git', '["Recipe discovery application powered by REST API integration for real-time data","Allows users to search recipes by ingredients, categories, or cuisine preferences","Features step-by-step cooking instructions with a clean and intuitive user interface"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Tenzies Dice Game', 'React, CSS, JavaScript', 'https://github.com/dlxks/tenzies.git', '["Interactive dice game where players roll dice until all match a target number","Includes win condition tracking, score recording, and game reset functionality","Playful and responsive UI design with smooth animations for an engaging user experience"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Code Rescue: Word Quest', 'React, CSS, JavaScript', 'https://github.com/dlxks/wordquest.git', '["Educational word puzzle game with a coding-inspired rescue mission theme","Progressive levels of difficulty to challenge players’ problem-solving and vocabulary","Clean and responsive UI design optimized for both desktop and mobile play"]');
INSERT INTO projects (title, technology, link, description) VALUES ('VanLife - Van Rental Platform', 'React, TypeScript, Vite, Tailwind CSS', 'https://github.com/dlxks/vanlife.git', '["Front-end design van rental platform designed for both travelers and van hosts","Advanced filtering and sorting options by van type (Simple, Rugged, Luxury) with dynamic UI updates","Host dashboard to manage van listings, availability, and customer reviews","Implemented simple secure authentication with protected routes and role-based access","Mobile-first approach using Tailwind CSS with scalable front-end architecture powered by Vite and TypeScript"]');
INSERT INTO projects (title, technology, link, description) VALUES ('Marci Metzger Landing Page', 'Next.js, Tailwind CSS', 'https://github.com/dlxks/marci-metzger.git', '["Modern landing page redesign for Marci Metzger’s real estate services","Responsive Next.js application showcasing property listings and services","Hero and About sections with engaging CTAs and detailed service info","Property highlights, gallery, and search functionality for easy browsing","Contact form and interactive map for seamless customer engagement","Deployed on Vercel with performance-optimized Next.js features"]');

-- Data for social_links
INSERT INTO social_links (platform, url, icon) VALUES ('Facebook', 'https://www.facebook.com/dot3stan/', 'bi:facebook');
INSERT INTO social_links (platform, url, icon) VALUES ('LinkedIn', 'https://www.linkedin.com/in/tristansangangbayan/', 'bi:linkedin');
INSERT INTO social_links (platform, url, icon) VALUES ('GitHub', 'https://github.com/dlxks', 'bi:github');
INSERT INTO social_links (platform, url, icon) VALUES ('Instagram', 'https://www.instagram.com/dot3stan/', 'bi:instagram');

